# Generated by Django 4.2.14 on 2024-07-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
    ]
